-- ============================================================================
-- NominaGT v4 - Tablas modulo RRHH (8 tablas)
-- Conexion: nominagt/NominaGT2026#@localhost:1521/xepdb1
-- ============================================================================

-- 1. EMPRESAS
CREATE TABLE empresas (
    empresa_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razon_social    VARCHAR2(150) NOT NULL,
    nit             VARCHAR2(15)  NOT NULL UNIQUE,
    direccion       VARCHAR2(255),
    telefono        VARCHAR2(20),
    email           VARCHAR2(100),
    representante_legal VARCHAR2(150),
    activo          NUMBER(1) DEFAULT 1 CHECK (activo IN (0,1)),
    creado_en       TIMESTAMP DEFAULT SYSTIMESTAMP,
    actualizado_en  TIMESTAMP
);

-- 2. SUCURSALES
CREATE TABLE sucursales (
    sucursal_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      NUMBER NOT NULL,
    nombre          VARCHAR2(100) NOT NULL,
    codigo          VARCHAR2(10)  NOT NULL,
    direccion       VARCHAR2(255),
    telefono        VARCHAR2(20),
    activo          NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_suc_emp FOREIGN KEY (empresa_id) REFERENCES empresas(empresa_id),
    CONSTRAINT uq_suc_codigo UNIQUE (empresa_id, codigo)
);

-- 3. DEPARTAMENTOS
CREATE TABLE departamentos (
    departamento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      NUMBER NOT NULL,
    nombre          VARCHAR2(100) NOT NULL,
    codigo          VARCHAR2(10)  NOT NULL,
    descripcion     VARCHAR2(255),
    activo          NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_dep_emp FOREIGN KEY (empresa_id) REFERENCES empresas(empresa_id),
    CONSTRAINT uq_dep_codigo UNIQUE (empresa_id, codigo)
);

-- 4. PUESTOS
CREATE TABLE puestos (
    puesto_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      NUMBER NOT NULL,
    nombre          VARCHAR2(100) NOT NULL,
    codigo          VARCHAR2(10)  NOT NULL,
    salario_minimo  NUMBER(12,2) DEFAULT 3166.28,
    salario_maximo  NUMBER(12,2),
    activo          NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_pue_emp FOREIGN KEY (empresa_id) REFERENCES empresas(empresa_id),
    CONSTRAINT uq_pue_codigo UNIQUE (empresa_id, codigo),
    CONSTRAINT ck_pue_salario CHECK (salario_minimo >= 3166.28)
);

-- 5. EMPLEADOS (la tabla central)
CREATE TABLE empleados (
    empleado_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id         NUMBER NOT NULL,
    sucursal_id        NUMBER,
    departamento_id    NUMBER,
    puesto_id          NUMBER,
    codigo_empleado    VARCHAR2(20) NOT NULL,
    primer_nombre      VARCHAR2(60) NOT NULL,
    segundo_nombre     VARCHAR2(60),
    primer_apellido    VARCHAR2(60) NOT NULL,
    segundo_apellido   VARCHAR2(60),
    apellido_casada    VARCHAR2(60),
    dpi                VARCHAR2(15) NOT NULL,
    nit                VARCHAR2(15),
    num_afiliacion_igss VARCHAR2(20),
    fecha_nacimiento   DATE NOT NULL,
    genero             CHAR(1) CHECK (genero IN ('M','F')),
    estado_civil       VARCHAR2(20) DEFAULT 'SOLTERO',
    direccion          VARCHAR2(255),
    telefono           VARCHAR2(20),
    email_corporativo  VARCHAR2(100),
    fecha_ingreso      DATE DEFAULT SYSDATE,
    estado             VARCHAR2(20) DEFAULT 'ACTIVO'
                       CHECK (estado IN ('ACTIVO','BAJA','SUSPENDIDO','VACACIONES')),
    motivo_baja        VARCHAR2(255),
    fecha_baja         DATE,
    creado_en          TIMESTAMP DEFAULT SYSTIMESTAMP,
    actualizado_en     TIMESTAMP,
    CONSTRAINT fk_emp_emp FOREIGN KEY (empresa_id)      REFERENCES empresas(empresa_id),
    CONSTRAINT fk_emp_suc FOREIGN KEY (sucursal_id)     REFERENCES sucursales(sucursal_id),
    CONSTRAINT fk_emp_dep FOREIGN KEY (departamento_id) REFERENCES departamentos(departamento_id),
    CONSTRAINT fk_emp_pue FOREIGN KEY (puesto_id)       REFERENCES puestos(puesto_id),
    CONSTRAINT uq_emp_codigo UNIQUE (empresa_id, codigo_empleado),
    CONSTRAINT uq_emp_dpi    UNIQUE (dpi)
);

-- 6. CONTRATOS LABORALES
CREATE TABLE contratos_laborales (
    contrato_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id      NUMBER NOT NULL,
    tipo_contrato    VARCHAR2(20) NOT NULL
                     CHECK (tipo_contrato IN ('INDEFINIDO','PLAZO_FIJO','TEMPORAL','PRUEBA')),
    fecha_inicio     DATE NOT NULL,
    fecha_fin        DATE,
    salario_base     NUMBER(12,2) NOT NULL,
    bonificacion     NUMBER(12,2) DEFAULT 250.00,
    jornada_laboral  VARCHAR2(20) DEFAULT 'DIURNA'
                     CHECK (jornada_laboral IN ('DIURNA','NOCTURNA','MIXTA')),
    forma_pago       VARCHAR2(20) DEFAULT 'MENSUAL'
                     CHECK (forma_pago IN ('MENSUAL','QUINCENAL','SEMANAL')),
    activo           NUMBER(1) DEFAULT 1,
    creado_en        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_cont_emp FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id),
    CONSTRAINT ck_cont_salario CHECK (salario_base >= 3166.28)
);

-- 7. CUENTAS BANCARIAS
CREATE TABLE cuentas_bancarias (
    cuenta_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id      NUMBER NOT NULL,
    banco_nombre     VARCHAR2(100) NOT NULL,
    banco_codigo     VARCHAR2(10),
    numero_cuenta    VARCHAR2(30) NOT NULL,
    tipo_cuenta      VARCHAR2(20) DEFAULT 'MONETARIA'
                     CHECK (tipo_cuenta IN ('MONETARIA','AHORRO')),
    es_principal     NUMBER(1) DEFAULT 1,
    activo           NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_cta_emp FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id)
);

-- 8. DEPENDIENTES
CREATE TABLE dependientes (
    dependiente_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id      NUMBER NOT NULL,
    parentesco       VARCHAR2(20) NOT NULL,
    nombre_completo  VARCHAR2(150) NOT NULL,
    fecha_nacimiento DATE,
    dpi              VARCHAR2(15),
    es_beneficiario  NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_dep_emp_dep FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id)
);

PROMPT Modulo RRHH creado: 8 tablas
