-- ============================================================================
-- NominaGT v4 - Tablas modulo Nomina (11 tablas)
-- ============================================================================

-- 9. PARAMETROS LEGALES
CREATE TABLE parametros_legales (
    parametro_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio                NUMBER(4) NOT NULL,
    igss_laboral_pct    NUMBER(5,4) DEFAULT 0.0483,
    igss_patronal_pct   NUMBER(5,4) DEFAULT 0.1267,
    salario_minimo      NUMBER(12,2) DEFAULT 3166.28,
    bonificacion_decreto NUMBER(12,2) DEFAULT 250.00,
    deduccion_personal_isr NUMBER(12,2) DEFAULT 48000.00,
    activo              NUMBER(1) DEFAULT 1,
    CONSTRAINT uq_param_anio UNIQUE (anio)
);

-- 10. TABLAS ISR
CREATE TABLE tablas_isr (
    rango_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio                NUMBER(4) NOT NULL,
    rango_min           NUMBER(12,2) NOT NULL,
    rango_max           NUMBER(12,2),
    impuesto_fijo       NUMBER(12,2) DEFAULT 0,
    porcentaje          NUMBER(5,4) NOT NULL,
    sobre_excedente_de  NUMBER(12,2) DEFAULT 0
);

-- 11. TIPOS DE INGRESO
CREATE TABLE tipos_ingreso (
    tipo_ingreso_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR2(20) NOT NULL UNIQUE,
    nombre              VARCHAR2(100) NOT NULL,
    afecta_igss         NUMBER(1) DEFAULT 1,
    afecta_isr          NUMBER(1) DEFAULT 1,
    es_calculado        NUMBER(1) DEFAULT 0,
    activo              NUMBER(1) DEFAULT 1
);

-- 12. TIPOS DE DEDUCCION
CREATE TABLE tipos_deduccion (
    tipo_deduccion_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR2(20) NOT NULL UNIQUE,
    nombre              VARCHAR2(100) NOT NULL,
    es_legal            NUMBER(1) DEFAULT 0,
    es_calculado        NUMBER(1) DEFAULT 0,
    activo              NUMBER(1) DEFAULT 1
);

-- 13. PERIODOS DE NOMINA
CREATE TABLE periodos_nomina (
    periodo_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id          NUMBER NOT NULL,
    anio                NUMBER(4) NOT NULL,
    mes                 NUMBER(2) NOT NULL CHECK (mes BETWEEN 1 AND 12),
    tipo_periodo        VARCHAR2(20) DEFAULT 'MENSUAL'
                        CHECK (tipo_periodo IN ('MENSUAL','QUINCENAL','BONO14','AGUINALDO')),
    fecha_inicio        DATE NOT NULL,
    fecha_fin           DATE NOT NULL,
    fecha_pago          DATE NOT NULL,
    estado              VARCHAR2(20) DEFAULT 'ABIERTO'
                        CHECK (estado IN ('ABIERTO','CALCULADO','APROBADO','PAGADO','CERRADO')),
    creado_por          VARCHAR2(50),
    aprobado_por        VARCHAR2(50),
    creado_en           TIMESTAMP DEFAULT SYSTIMESTAMP,
    aprobado_en         TIMESTAMP,
    CONSTRAINT fk_per_emp FOREIGN KEY (empresa_id) REFERENCES empresas(empresa_id),
    CONSTRAINT uq_periodo UNIQUE (empresa_id, anio, mes, tipo_periodo)
);

-- 14. NOMINA ENCABEZADO
CREATE TABLE nomina_encabezado (
    nomina_enc_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id          NUMBER NOT NULL,
    empleado_id         NUMBER NOT NULL,
    salario_base        NUMBER(12,2) NOT NULL,
    total_ingresos      NUMBER(12,2) DEFAULT 0,
    total_deducciones   NUMBER(12,2) DEFAULT 0,
    salario_neto        NUMBER(12,2) DEFAULT 0,
    estado              VARCHAR2(20) DEFAULT 'CALCULADO'
                        CHECK (estado IN ('CALCULADO','APROBADO','PAGADO')),
    creado_en           TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ne_per FOREIGN KEY (periodo_id)  REFERENCES periodos_nomina(periodo_id),
    CONSTRAINT fk_ne_emp FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id),
    CONSTRAINT uq_ne UNIQUE (periodo_id, empleado_id)
);

-- 15. NOMINA DETALLE
CREATE TABLE nomina_detalle (
    nomina_det_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomina_enc_id       NUMBER NOT NULL,
    tipo_movimiento     CHAR(1) NOT NULL CHECK (tipo_movimiento IN ('I','D')),
    concepto            VARCHAR2(100) NOT NULL,
    monto               NUMBER(12,2) NOT NULL,
    es_calculado        NUMBER(1) DEFAULT 1,
    referencia          VARCHAR2(100),
    CONSTRAINT fk_nd_ne FOREIGN KEY (nomina_enc_id) REFERENCES nomina_encabezado(nomina_enc_id) ON DELETE CASCADE
);

-- 16. PRESTAMOS
CREATE TABLE prestamos (
    prestamo_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id         NUMBER NOT NULL,
    descripcion         VARCHAR2(255) NOT NULL,
    monto_original      NUMBER(12,2) NOT NULL,
    saldo_pendiente     NUMBER(12,2) NOT NULL,
    cuota_mensual       NUMBER(12,2) NOT NULL,
    numero_cuotas       NUMBER(3) NOT NULL,
    cuotas_pagadas      NUMBER(3) DEFAULT 0,
    fecha_inicio        DATE DEFAULT SYSDATE,
    estado              VARCHAR2(20) DEFAULT 'VIGENTE'
                        CHECK (estado IN ('VIGENTE','PAGADO','CANCELADO','SUSPENDIDO')),
    CONSTRAINT fk_pres_emp FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id)
);

-- 17. CUOTAS DE PRESTAMOS
CREATE TABLE cuotas_prestamo (
    cuota_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestamo_id         NUMBER NOT NULL,
    nomina_enc_id       NUMBER,
    numero_cuota        NUMBER(3) NOT NULL,
    monto               NUMBER(12,2) NOT NULL,
    fecha_descuento     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_cp_pres FOREIGN KEY (prestamo_id)   REFERENCES prestamos(prestamo_id),
    CONSTRAINT fk_cp_ne   FOREIGN KEY (nomina_enc_id) REFERENCES nomina_encabezado(nomina_enc_id)
);

-- 18. CONCEPTOS ADICIONALES
CREATE TABLE conceptos_adicionales (
    concepto_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id         NUMBER NOT NULL,
    periodo_id          NUMBER NOT NULL,
    tipo                CHAR(1) CHECK (tipo IN ('I','D')),
    descripcion         VARCHAR2(255) NOT NULL,
    monto               NUMBER(12,2) NOT NULL,
    aplicado            NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_ca_emp FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id),
    CONSTRAINT fk_ca_per FOREIGN KEY (periodo_id)  REFERENCES periodos_nomina(periodo_id)
);

-- 19. VACACIONES
CREATE TABLE vacaciones (
    vacacion_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id         NUMBER NOT NULL,
    anio_periodo        NUMBER(4) NOT NULL,
    dias_disponibles    NUMBER(3) DEFAULT 15,
    dias_tomados        NUMBER(3) DEFAULT 0,
    saldo               NUMBER(3),
    estado              VARCHAR2(20) DEFAULT 'PENDIENTE',
    CONSTRAINT fk_vac_emp FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id)
);

PROMPT Modulo Nomina creado: 11 tablas
