-- ============================================================================
-- NominaGT v4 - Tablas modulo Contabilidad (4 tablas)
-- ============================================================================

-- 20. CUENTAS CONTABLES
CREATE TABLE cuentas_contables (
    cuenta_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id          NUMBER NOT NULL,
    codigo              VARCHAR2(20) NOT NULL,
    nombre              VARCHAR2(150) NOT NULL,
    tipo                VARCHAR2(20) CHECK (tipo IN ('ACTIVO','PASIVO','PATRIMONIO','INGRESO','GASTO')),
    naturaleza          CHAR(1) CHECK (naturaleza IN ('D','C')),
    activo              NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_cc_emp FOREIGN KEY (empresa_id) REFERENCES empresas(empresa_id),
    CONSTRAINT uq_cc_codigo UNIQUE (empresa_id, codigo)
);

-- 21. PARTIDAS CONTABLES
CREATE TABLE partidas_contables (
    partida_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id          NUMBER NOT NULL,
    fecha               DATE DEFAULT SYSDATE,
    descripcion         VARCHAR2(255),
    total_debe          NUMBER(14,2) DEFAULT 0,
    total_haber         NUMBER(14,2) DEFAULT 0,
    estado              VARCHAR2(20) DEFAULT 'BORRADOR',
    creado_por          VARCHAR2(50),
    creado_en           TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_pc_per FOREIGN KEY (periodo_id) REFERENCES periodos_nomina(periodo_id)
);

-- 22. DETALLE DE PARTIDAS
CREATE TABLE partidas_detalle (
    detalle_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partida_id          NUMBER NOT NULL,
    cuenta_id           NUMBER NOT NULL,
    descripcion         VARCHAR2(255),
    debe                NUMBER(14,2) DEFAULT 0,
    haber               NUMBER(14,2) DEFAULT 0,
    CONSTRAINT fk_pd_par FOREIGN KEY (partida_id) REFERENCES partidas_contables(partida_id) ON DELETE CASCADE,
    CONSTRAINT fk_pd_cue FOREIGN KEY (cuenta_id)  REFERENCES cuentas_contables(cuenta_id)
);

-- 23. ARCHIVOS BANCARIOS (ACH generados)
CREATE TABLE archivos_bancarios (
    archivo_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id          NUMBER NOT NULL,
    banco               VARCHAR2(50) NOT NULL,
    nombre_archivo      VARCHAR2(255),
    contenido           CLOB,
    total_registros     NUMBER(6),
    monto_total         NUMBER(14,2),
    estado              VARCHAR2(20) DEFAULT 'GENERADO',
    generado_en         TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ab_per FOREIGN KEY (periodo_id) REFERENCES periodos_nomina(periodo_id)
);

PROMPT Modulo Contabilidad creado: 4 tablas
