-- ============================================================================
-- NominaGT v4 - Tablas modulo Seguridad (5 tablas)
-- ============================================================================

-- 24. ROLES
CREATE TABLE roles (
    rol_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(50) NOT NULL UNIQUE,
    descripcion         VARCHAR2(255),
    es_sistema          NUMBER(1) DEFAULT 0
);

-- 25. USUARIOS
CREATE TABLE usuarios (
    usuario_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id          NUMBER NOT NULL,
    empleado_id         NUMBER,
    nombre_usuario      VARCHAR2(50) NOT NULL UNIQUE,
    email               VARCHAR2(100) NOT NULL UNIQUE,
    password_hash       VARCHAR2(255) NOT NULL,
    refresh_token       VARCHAR2(500),
    refresh_expira      TIMESTAMP,
    activo              NUMBER(1) DEFAULT 1,
    intentos_fallidos   NUMBER(3) DEFAULT 0,
    bloqueado_hasta     TIMESTAMP,
    ultimo_acceso       TIMESTAMP,
    creado_en           TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_usr_emp FOREIGN KEY (empresa_id)  REFERENCES empresas(empresa_id),
    CONSTRAINT fk_usr_emp2 FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id)
);

-- 26. USUARIO_ROLES
CREATE TABLE usuario_roles (
    usuario_id          NUMBER NOT NULL,
    rol_id              NUMBER NOT NULL,
    asignado_en         TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_usr_rol PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_ur_usr FOREIGN KEY (usuario_id) REFERENCES usuarios(usuario_id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_rol FOREIGN KEY (rol_id)     REFERENCES roles(rol_id)        ON DELETE CASCADE
);

-- 27. ROL_PERMISOS
CREATE TABLE rol_permisos (
    permiso_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id              NUMBER NOT NULL,
    modulo              VARCHAR2(50) NOT NULL,
    permiso             VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_rp_rol FOREIGN KEY (rol_id) REFERENCES roles(rol_id) ON DELETE CASCADE,
    CONSTRAINT uq_rp UNIQUE (rol_id, modulo, permiso)
);

-- 28. AUDITORIA
CREATE TABLE auditoria (
    auditoria_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario             VARCHAR2(50),
    accion              VARCHAR2(20) CHECK (accion IN ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT','EXPORT')),
    tabla               VARCHAR2(50),
    registro_id         NUMBER,
    valor_anterior      CLOB,
    valor_nuevo         CLOB,
    ip                  VARCHAR2(45),
    user_agent          VARCHAR2(255),
    fecha               TIMESTAMP DEFAULT SYSTIMESTAMP
);

PROMPT Modulo Seguridad creado: 5 tablas. TOTAL: 28 tablas
