-- ============================================================================
-- NominaGT v4 - Modulo de Vacaciones (Codigo de Trabajo art. 130)
--
-- Reemplaza la tabla 'vacaciones' resumen por una de detalle: cada fila
-- representa un periodo solicitado/gozado por un empleado.
--
-- Saldo se calcula dinamicamente:
--   dias_acumulados = anios_trabajados * 15
--   dias_gozados    = SUM(dias) WHERE estado IN ('APROBADA','GOZADA')
--   pendientes      = acumulados - gozados
-- ============================================================================

-- 1. Borrar vista/tabla resumen y refactorizar
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'VACACIONES';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE vacaciones CASCADE CONSTRAINTS';
    END IF;
END;
/

CREATE TABLE vacaciones (
    vacacion_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id     NUMBER NOT NULL,
    fecha_inicio    DATE NOT NULL,
    fecha_fin       DATE NOT NULL,
    dias            NUMBER(3) NOT NULL CHECK (dias > 0 AND dias <= 365),
    motivo          VARCHAR2(500),
    estado          VARCHAR2(20) DEFAULT 'SOLICITADA'
                    CHECK (estado IN ('SOLICITADA','APROBADA','RECHAZADA','GOZADA','CANCELADA')),
    solicitado_por  VARCHAR2(50),
    solicitado_en   TIMESTAMP DEFAULT SYSTIMESTAMP,
    aprobado_por    VARCHAR2(50),
    aprobado_en     TIMESTAMP,
    observaciones   VARCHAR2(500),
    CONSTRAINT fk_vac_emp FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id),
    CONSTRAINT chk_vac_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE INDEX ix_vac_empleado ON vacaciones(empleado_id);
CREATE INDEX ix_vac_estado ON vacaciones(estado);
CREATE INDEX ix_vac_fechas ON vacaciones(fecha_inicio, fecha_fin);

-- 2. Vista de saldo por empleado
CREATE OR REPLACE VIEW vw_vacaciones_saldo AS
SELECT
    e.empleado_id,
    e.codigo_empleado,
    e.primer_nombre || ' ' || e.primer_apellido AS nombre,
    c.fecha_inicio AS fecha_inicio_contrato,
    -- anios cumplidos al dia de hoy
    FLOOR(MONTHS_BETWEEN(SYSDATE, c.fecha_inicio) / 12) AS anios_trabajados,
    FLOOR(MONTHS_BETWEEN(SYSDATE, c.fecha_inicio) / 12) * 15 AS dias_acumulados,
    NVL((SELECT SUM(v.dias) FROM vacaciones v
          WHERE v.empleado_id = e.empleado_id
            AND v.estado IN ('APROBADA','GOZADA')), 0) AS dias_gozados,
    FLOOR(MONTHS_BETWEEN(SYSDATE, c.fecha_inicio) / 12) * 15
    - NVL((SELECT SUM(v.dias) FROM vacaciones v
            WHERE v.empleado_id = e.empleado_id
              AND v.estado IN ('APROBADA','GOZADA')), 0) AS dias_pendientes,
    NVL((SELECT SUM(v.dias) FROM vacaciones v
          WHERE v.empleado_id = e.empleado_id
            AND v.estado = 'SOLICITADA'), 0) AS dias_en_solicitud
FROM empleados e
LEFT JOIN contratos_laborales c ON c.empleado_id = e.empleado_id AND c.activo = 1
WHERE e.estado = 'ACTIVO';

PROMPT Modulo de vacaciones listo: tabla + indices + vista de saldo.
