-- ============================================================================
-- NominaGT v4 - Modulo de Liquidaciones / Finiquito
--
-- Cuando se da de baja a un empleado se calculan las prestaciones laborales
-- exigidas por el Codigo de Trabajo de Guatemala:
--   - Indemnizacion: 1 mes de salario por año trabajado (art. 82-90)
--   - Aguinaldo proporcional (art. 137 + Decreto 76-78)
--   - Bono 14 proporcional (Decreto 42-92)
--   - Vacaciones no gozadas (15 días/año - art. 130)
--
-- Esta tabla guarda el registro de cada liquidacion calculada.
-- ============================================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'LIQUIDACIONES';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE liquidaciones CASCADE CONSTRAINTS';
    END IF;
END;
/

CREATE TABLE liquidaciones (
    liquidacion_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id           NUMBER NOT NULL,
    fecha_inicio_contrato DATE NOT NULL,
    fecha_baja            DATE NOT NULL,
    motivo                VARCHAR2(20) NOT NULL
                          CHECK (motivo IN ('RENUNCIA','DESPIDO_JUSTIFICADO',
                                            'DESPIDO_INJUSTIFICADO','MUTUO_ACUERDO',
                                            'JUBILACION','FALLECIMIENTO','OTRO')),
    motivo_detalle        VARCHAR2(500),

    -- Datos para el cálculo
    salario_base          NUMBER(12,2) NOT NULL,
    salario_diario        NUMBER(12,2) NOT NULL,
    anios_servicio        NUMBER(6,3)  NOT NULL,
    dias_servicio_total   NUMBER(6,0)  NOT NULL,

    -- Prestaciones
    indemnizacion         NUMBER(12,2) DEFAULT 0,
    bono14_proporcional   NUMBER(12,2) DEFAULT 0,
    aguinaldo_proporcional NUMBER(12,2) DEFAULT 0,
    vacaciones_no_gozadas NUMBER(12,2) DEFAULT 0,
    dias_vacaciones_pend  NUMBER(5,0)  DEFAULT 0,
    otros_pagos           NUMBER(12,2) DEFAULT 0,
    descuentos            NUMBER(12,2) DEFAULT 0,
    total                 NUMBER(12,2) NOT NULL,

    -- Auditoria
    estado                VARCHAR2(20) DEFAULT 'CALCULADA'
                          CHECK (estado IN ('CALCULADA','APROBADA','PAGADA','ANULADA')),
    calculado_por         VARCHAR2(50),
    calculado_en          TIMESTAMP DEFAULT SYSTIMESTAMP,
    aprobado_por          VARCHAR2(50),
    aprobado_en           TIMESTAMP,
    observaciones         VARCHAR2(1000),

    CONSTRAINT fk_liq_emp FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id)
);

CREATE INDEX ix_liq_empleado ON liquidaciones(empleado_id);
CREATE INDEX ix_liq_fecha    ON liquidaciones(fecha_baja);

PROMPT Tabla liquidaciones creada.
